# Generated by Django 5.0.3 on 2024-03-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auction_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='store.pet'),
        ),
    ]
